from enum import Enum


class State:
    INPUT_NAME = "INPUT_NAME"
    MAIN = "MAIN"
    GROUP_CREATING = "GROUP_CREATING"
    GROUP_JOINING = "GROUP_JOINING"
    GROUP = "GROUP"
    QUEUE_CREATING = "QUEUE_CREATING"
    QUEUE = "QUEUE"
