# Generated by Django 2.2.23 on 2021-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField(verbose_name='ID пользователя в тг')),
                ('name', models.TextField(verbose_name='Имя пользователя в тг')),
                ('state', models.CharField(max_length=30, verbose_name='Текущее состояние чата')),
            ],
        ),
    ]
