# Generated by Django 2.2.23 on 2021-05-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20210524_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=30, verbose_name='Текущее состояние чата'),
        ),
    ]
