# Generated by Django 2.2.23 on 2021-05-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20210524_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя группы')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('MAIN', 'MAIN'), ('GROUP_CREATING_INPUT_GROUP', 'GROUP_CREATING_INPUT_GROUP'), ('GROUP_CREATING_INPUT_NAME', 'GROUP_CREATING_INPUT_NAME'), ('GROUP_JOINING_INPUT_GROUP', 'GROUP_JOINING_INPUT_GROUP'), ('GROUP_JOINING_INPUT_NAME', 'GROUP_JOINING_INPUT_NAME'), ('GROUP', 'GROUP'), ('GROUP_CREATING', 'GROUP_CREATING')], max_length=30, verbose_name='Текущее состояние чата'),
        ),
    ]
