# Generated by Django 2.2.23 on 2021-05-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_auto_20210525_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
