# Generated by Django 2.2.23 on 2021-05-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0009_queue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'Очередь', 'verbose_name_plural': 'Очереди'},
        ),
        migrations.AddField(
            model_name='queue',
            name='users',
            field=models.ManyToManyField(null=True, to='ugc.User', verbose_name='Участники очереди'),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group0', to='ugc.User', verbose_name='Админ'),
        ),
    ]
