# Generated by Django 2.2.23 on 2021-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0010_auto_20210526_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='users',
            field=models.ManyToManyField(to='ugc.User', verbose_name='Участники очереди'),
        ),
    ]
