# Generated by Django 2.2.23 on 2021-05-26 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0011_auto_20210526_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя группы'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='users',
            field=models.ManyToManyField(blank=True, to='ugc.User', verbose_name='Участники очереди'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ugc.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя пользователя в тг'),
        ),
    ]
