# Generated by Django 2.2.23 on 2021-05-26 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0013_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=32, null=True, verbose_name='Отображаемое имя пользователя'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='ugc.User', verbose_name='Создатель очереди'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('INPUT_NAME', 'INPUT_NAME'), ('MAIN', 'MAIN'), ('GROUP_CREATING', 'GROUP_CREATING'), ('GROUP_JOINING', 'GROUP_JOINING'), ('GROUP', 'GROUP'), ('QUEUE', 'QUEUE')], max_length=30, verbose_name='Текущее состояние чата'),
        ),
    ]
