# Generated by Django 2.2.23 on 2021-05-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0014_auto_20210527_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='ugc.Group', verbose_name='Группа'),
        ),
    ]
