# Generated by Django 2.2.23 on 2021-05-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0020_remove_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя очереди'),
        ),
    ]
