# Generated by Django 2.2.23 on 2021-05-26 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0021_auto_20210527_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='ugc.User', verbose_name='Создатель очереди'),
        ),
    ]
