# Generated by Django 2.2.23 on 2021-05-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0022_queue_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
