# Generated by Django 2.2.23 on 2021-05-26 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0023_auto_20210527_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя группы'),
        ),
        migrations.AddField(
            model_name='queue',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='ugc.User', verbose_name='Создатель очереди'),
        ),
        migrations.AddField(
            model_name='queue',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='Имя очереди'),
        ),
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.PositiveIntegerField(null=True, verbose_name='ID пользователя в тг'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=32, null=True, verbose_name='Отображаемое имя пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ugc.Group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='Имя пользователя в тг'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('INPUT_NAME', 'INPUT_NAME'), ('MAIN', 'MAIN'), ('GROUP_CREATING', 'GROUP_CREATING'), ('GROUP_JOINING', 'GROUP_JOINING'), ('GROUP', 'GROUP'), ('QUEUE', 'QUEUE')], max_length=30, null=True, verbose_name='Текущее состояние чата'),
        ),
    ]
