# Generated by Django 2.2.23 on 2021-05-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0027_auto_20210527_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата события'),
        ),
        migrations.AddField(
            model_name='queue',
            name='users',
            field=models.ManyToManyField(blank=True, to='ugc.User', verbose_name='Участники очереди'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='Название очереди'),
        ),
    ]
