# Generated by Django 2.2.23 on 2021-05-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0028_auto_20210527_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmp_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users0', to='ugc.Queue', verbose_name='Текушая очередь'),
        ),
    ]
